version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "antwanchild"
    commit-message:
      prefix: "chore"
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "antwanchild"
    commit-message:
      prefix: "chore"
    rebase-strategy: "auto"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "antwanchild"
    commit-message:
      prefix: "chore"
    rebase-strategy: "auto"
